# Cargo audit configuration
# List known vulnerabilities that are accepted with justification

[advisories]
# Example format:
# ignore = [
#     "RUSTSEC-2024-0001", # Reason: Fixed in our code by...
# ]
ignore = []