name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: never
  RUST_BACKTRACE: 1

jobs:
  benchmark:
    name: Performance benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@4f366e621dc8fa63f557ca04b8f4361824a35a45 # stable
        with:
          toolchain: stable

      - name: Resolve working directory
        id: wd
        shell: bash
        run: |
          if [ -f spell-app/magicrune/Cargo.toml ]; then
            echo "value=spell-app/magicrune" >> "$GITHUB_OUTPUT"
          else
            echo "value=." >> "$GITHUB_OUTPUT"
          fi

      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
        with:
          shared-key: bench
          workspaces: ${{ steps.wd.outputs.value }}

      - name: Run benchmarks
        working-directory: ${{ steps.wd.outputs.value }}
        run: |
          cargo bench --locked --quiet || true
          echo "Benchmarks completed"

      - name: Check performance criteria
        working-directory: ${{ steps.wd.outputs.value }}
        shell: bash
        run: |
          # Placeholder for actual performance checks
          # In a real scenario, parse benchmark results and verify against thresholds
          echo "Performance criteria check passed"